### ISSUE TITLE
Equation BevHolt

### ISSUE THREAD

**Issue by Isabella84** [ices-tools-prod/msy#10]
Hello everybody, 
I would like to know which formulation of Beverton and Holt stock-recruitment equation is used in Eqsim. I tried to use the coefficients to re-estimate the recruitmen on my dataset, but unsuccessfully. The unit of estimated recruitment are completely out of scale.
Could you help me, please?
Thank you in advance.
Isabella

**Comment by colinpmillar** [comment]
Hi Isabella,

You can find the definitions of the Beverton model:
https://github.com/ices-tools-prod/msy/blob/master/R/myMH.R#L60

and an alternative formulation:
https://github.com/ices-tools-prod/msy/blob/master/R/myMH.R#L85

HTH,
Colin

**Comment by Isabella84** [comment]
Perfect! Thank you very much Colin!
