### ISSUE TITLE
Option to define breakpoint for segmented regresssion

### ISSUE THREAD

**Issue by Isabella84** [ices-tools-prod/msy#12]
Dear developpers, I would like to know if is possibile to fix the breakpoint of a segmented regression stock-recruitment relationship recalling eqsr_fit function. From the help it seems not possible to me.
Thank you in advance,
Isabella

**Comment by Milldaz** [comment]
Hi Isabella,

You can fix the breakpoint in the segmented regression by creating your own SRR function. e.g.:
## determine segreg model with breakpoint at 'breakPt'
breakPt<- xxxx
SegregBP  <- function(ab, ssb) log(ifelse(ssb >= breakPt, ab$a * breakPt, ab$a * ssb))
FIT_segregBP <- eqsr_fit(stock, nsamp=1000, models = "SegregBP ")

Cheers,
David

**Comment by Isabella84** [comment]
Thank you David, it seems to work! ;)
Cheers,
Isabella
