### ISSUE TITLE
eqsim_run not working for ssb_lag>1

### ISSUE THREAD

**Issue by vtrijoulet** [ices-tools-prod/msy#24]
I think the last commit in eqsim_run induces a problem if ssb_lag>1

For instance, if ssb_lag=3:

_for (j in 2:pmax(2, ssb_lag)) {
      Ny[,j,] <- rbind(N1[1:(ages-1),], colSums(N1[ages:50,]))
      ssby[j,] <- colSums(Mat[,rsam[j-1,]] * Ny[,1,] * west[,rsam[j-1,]] / exp(Zpre))
    }_
Here j goes from 2 to 3 and the ssby matrix fills up to j=3

   _for (j in (2+ssb_lag):Nrun) {
      Fnext <- Fbar * pmin(1, ssby[j-1,] * exp(SSBerr[j-1,]) / Btrigger)
...._

But here j goes from 5 to Nrun. 
So ssby[4,] being 0, we get NaN for Fnext

**Comment by colinpmillar** [comment]
Thanks!
I will look into that asap,
Cheers,
Colin
