### ISSUE TITLE
Delicate handling of years arguments

### ISSUE THREAD

**Issue by iagomosqueira** [ices-tools-prod/msy#25]
The years arguments of `eqsim_run` extract start and end from the first and second, but do not warn or stop if arguments are of length > 2. I think it should check for length of `bio.years` and `sel.years`. If a vector of years is passed, it will run but only use the first two.

```
  if(length(bio.years) > 2)
    stop("bio.years must be given as a length two vector: c(first, last)")
  if(length(sel.years) > 2)
    stop("sel.years must be given as a length two vector: c(first, last)")
```

Also, the default value for both arguments is set to be five years starting with the one before the last year in the model. But the guidelines suggest using as default the last ten years, without any year apparently being dropped. It might be better than the default argument matches the default set up in the guidelines, unless I am missing something.

**Comment by colinpmillar** [comment]
Thanks for this - will implement :)

**Comment by colinpmillar** [comment]
implemented in 
9fceec8
continued in #26
