### ISSUE TITLE
icesTAF v4 does not have "msg" function anymore

### ISSUE THREAD

**Issue by alko989** [ices-tools-prod/msy#32]
`icesTAF::msg` is used twice in [eqsim_run.R](https://github.com/ices-tools-prod/msy/blob/2b0c10dc0b76df1a52a3694767c898c8f839b674/R/eqsim_run.R), haven't seen it in other places. It should be changed to `TAF::msg`

**Comment by colinpmillar** [comment]
Thank you! I think I will fix so thaty icesTAF:: can inherit from TAF::  I did think of this, but didnt realise the impact at the time.

Will let you know when icesTAF is updated and published on CRAN.

**Comment by colinpmillar** [comment]
I have fixed here: https://github.com/ices-tools-prod/icesTAF/commit/a8d2971598bf6bc4f1656432e275df4c51a89127

and submitted to CRAN, hopefully will up and running by tomorrow. In the mean time you can install using devtools or from here: 
https://ices-tools-prod.r-universe.dev/ui#package:icesTAF

Thanks for the heads up!

**Comment by colinpmillar** [comment]
@alko989 on CRAN now :)
