### ISSUE TITLE
Won't install in R 3.3.1

### ISSUE THREAD

**Issue by Milldaz** [ices-tools-prod/msy#5]
Seems to have a faulty description file:
> install_github("wgmg/msy")
Downloading GitHub repo wgmg/msy@master from URL https://api.github.com/repos/wgmg/msy/zipball/master
Installing msy
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/david.miller/AppData/Local/Temp/RtmpOQCTsB/devtools2a1c2f6c3fa0/wgmg-msy-b32810a"  \
  --library="E:/Profile/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'msy' ...
Error : Invalid DESCRIPTION file
Malformed Authors@R field:   missing value where TRUE/FALSE needed
See section 'The DESCRIPTION file' in the 'Writing R Extensions' manual.
ERROR: installing package DESCRIPTION failed for package 'msy'
* removing 'E:/Profile/Documents/R/win-library/3.3/msy'
Error: Command failed (1)

**Comment by einarhjorleifsson** [comment]
are you, colin taking this forward (as an ices baby) or should i still be messing around in?
einar

**Comment by colinpmillar** [comment]
Hi Eirnar, i will give it a go, and post here how I get on.

**Comment by colinpmillar** [comment]
The problem is related only to the current release version of R - this error does not occur with the previous (as we know) or the development version, so seems to be something they have put in and then are removing straight away... anyway I will fix it.
