### ISSUE TITLE
problems with installation Eqsim

### ISSUE THREAD

**Issue by Isabella84** [ices-tools-prod/msy#6]
Hello everybody,
I would like to play with Eqsim package, but when I tried to install it (I am using R version 3.1.1)
There is a binary version available (and will be installed) but when I try to launch, I have this type of error:

  **source version is later:
             binary       source
FLCore 2.5.20150116 2.5.20160504

trying URL 'http://flr-project.org/R/bin/windows/contrib/3.1/FLCore_2.5.20150116.zip'
Content type 'application/zip' length 1084702 bytes (1.0 Mb)
opened URL
downloaded 1.0 Mb

package ‘FLCore’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Utente\AppData\Local\Temp\RtmpItEgKf\downloaded_packages
Downloading GitHub repo ices-tools-prod/msy@master
from URL https://api.github.com/repos/ices-tools-prod/msy/zipball/master
Installing msy
Error in `_digest`(c(list(repos, type), lapply(`_additional`, function(x) eval(x[[2L]],  : 
  object 'digest_impl' not found
In addition: Warning message:
package ‘devtools’ was built under R version 3.1.3** 

The R code that I typed is:

**install.packages("FLCore", repo = "http://flr-project.org/R")
library(devtools)
install_github("ices-tools-prod/msy")**

Even with version 3.1.3 I have the same error. What's wrong?
Thank you to who will help me.
Ciao,
Isabella

**Comment by colinpmillar** [comment]
Hi Isabella,
It looks like you may need to install devtools again as the digest package is a dependency of devtools.
I might also suggest upgrading to R 3.3.1.  The version of R you are using was release around October 2014 so is quite old and may also be causing some problems.
Let us know if this solves the issue.
Best,
Colin.

**Comment by colinpmillar** [comment]
Have tested on a fresh install of R 331 and installs fine, going close this issue

**Comment by Isabella84** [comment]
Thank you very much Colin, I tried too and it works.
Just a warning: in the method eqsr_fit the model smooth_hockey is evocated still
without capital in the first letter.
Keep in touch!
Ciao,
Isabella

**Comment by colinpmillar** [comment]
Thanks Isabella :+1: , will add this to a new issue #7
