### ISSUE TITLE
Code bug

### ISSUE THREAD

**Issue by hoski** [ices-tools-prod/msy#9]
in the function eqsr_Buckland

 dimnames(pred) <- list(model = fit$model, ssb = data$ssb)

should change to 

dimnames(pred) <- list(model = fit$model, ssb = sort(data$ssb))

In line with how pred is generated.  

Should not matter in the simulations that used the parameters, not those predictions.

**Comment by colinpmillar** [comment]
Fix implemented on development branch and will push to master soon
